# Generated by Django 5.1.6 on 2026-08-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_audiosubmission_analysis_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiosubmission',
            name='loudness_dbfs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiosubmission',
            name='file_size_bytes',
            field=models.PositiveIntegerField(),
        ),
    ]
