# Generated by Django 5.1.6 on 2026-08-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_years', models.FloatField(blank=True, null=True)),
                ('current_ctc', models.IntegerField(blank=True, null=True)),
                ('applied_date', models.DateField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('rate', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('verified', models.CharField(blank=True, max_length=10, null=True)),
                ('projects_completed', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
